import QRCode from 'qrcode';
import jsQR from 'jsqr';
import { PROTOCOL, PROFILES, FountainDecoder, base64ToBytes, bytesToBase64, checksum, createSymbol, splitIntoBlocks } from './protocol.js';
import './style.css';
import './upgrades.css';

const app=document.querySelector('#app');
const state={stream:null,scanId:0,sendTimer:0,wakeLock:null,running:false,paused:false,blocks:[],manifest:null,decoder:null,startedAt:0,symbolId:0,valid:0,duplicate:0,invalid:0,lastScan:0};
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c]);
const size=n=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
const time=s=>`${Math.floor(s/60).toString().padStart(2,'0')}:${Math.floor(s%60).toString().padStart(2,'0')}`;
const hex=b=>[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('');
function shell(content){app.innerHTML=`<div class="glow"></div><header><button class="brand" data-home><span class="logo">▦</span> QRBEAM <sup>2</sup></button><span class="secure"><i></i> Uçtan uca yerel</span></header><main>${content}</main><footer>Sunucu yok · Hesap yok · Yalnızca ışık</footer>`;document.querySelector('[data-home]')?.addEventListener('click',home);}
function home(){stopAll();shell(`<section class="hero"><div class="eyebrow">KAYIP TOLERANSLI OPTİK AKTARIM</div><h1>Dosyanı havadan değil,<br><em>ışıktan geçir.</em></h1><p>QRBeam 2, kaçan kamera karelerini rateless XOR sembolleriyle telafi eder. Dosya yalnızca SHA‑256 birebir doğrulanırsa kaydedilir.</p><div class="feature-row"><span>⚡ 26 FPS</span><span>◈ Fountain recovery</span><span>✓ SHA‑256</span></div><div class="choices"><button class="choice" id="send"><span class="choice-icon">↗</span><b>Dosya Gönder</b><small>Akıllı, kesintisiz QR yayını başlat</small><span class="arrow">→</span></button><button class="choice" id="receive"><span class="choice-icon purple">⌗</span><b>Dosya Al</b><small>Kamerayla tara, doğrula ve kaydet</small><span class="arrow">→</span></button></div><div class="privacy"><span>◈</span><div><b>Verilerin sana ait kalır</b><small>Dosyalar ve kamera görüntüsü cihazdan ayrılmaz.</small></div></div></section>`);document.querySelector('#send').onclick=sendPage;document.querySelector('#receive').onclick=receivePage;}
function sendPage(){stopAll();shell(`<section class="panel"><button class="back" data-home>← Ana sayfa</button><div class="eyebrow">GÖNDERİCİ</div><h2>Dosya ve hız profili</h2><p>Dengeli profil çoğu telefon için en iyi hız/güvenilirlik oranını sunar.</p><div class="profiles">${Object.entries(PROFILES).map(([k,p])=>`<label class="profile ${k==='balanced'?'selected':''}"><input type="radio" name="profile" value="${k}" ${k==='balanced'?'checked':''}><b>${p.label}</b><span>${p.fps} FPS · ${p.blockSize} B</span><small>${p.note}</small></label>`).join('')}</div><label class="drop"><input id="file" type="file"><span class="upload">↑</span><b>Dosya seçmek için dokun</b><small>Her tür dosya desteklenir</small></label><div id="fileInfo"></div></section>`);document.querySelector('[data-home]').onclick=home;document.querySelectorAll('.profile input').forEach(input=>input.onchange=()=>{document.querySelectorAll('.profile').forEach(x=>x.classList.remove('selected'));input.closest('.profile').classList.add('selected');});document.querySelector('#file').onchange=prepareFile;}
async function prepareFile(e){const file=e.target.files[0];if(!file)return;const box=document.querySelector('#fileInfo');box.innerHTML='<div class="loading">SHA‑256 hesaplanıyor ve bloklar hazırlanıyor…</div>';const raw=new Uint8Array(await file.arrayBuffer()),profileKey=document.querySelector('input[name="profile"]:checked').value,profile=PROFILES[profileKey],digest=hex(await crypto.subtle.digest('SHA-256',raw));state.blocks=splitIntoBlocks(raw,profile.blockSize);state.manifest={p:PROTOCOL,t:'m',id:crypto.randomUUID().slice(0,12),n:file.name,z:file.size,m:file.type||'application/octet-stream',h:digest,k:state.blocks.length,b:profile.blockSize,pf:profileKey};box.innerHTML=`<div class="file-card"><div class="file-icon">◆</div><div><b>${esc(file.name)}</b><small>${size(file.size)} · ${state.blocks.length} kaynak blok · SHA‑256 hazır</small></div></div><div class="notice success">Kayıp kare toleransı etkin. Yayın, alıcı tamamlayana kadar sınırsız yeni sembol üretir.</div><button class="primary" id="start">Optik aktarımı başlat <span>→</span></button>`;document.querySelector('#start').onclick=()=>startSending(file,profile);}
async function startSending(file,profile){state.running=true;state.paused=false;state.symbolId=0;state.startedAt=performance.now();await requestWakeLock();shell(`<section class="transmit"><button class="back" id="finish">← Bitir</button><div class="eyebrow live"><i></i> YAYINDA · ${profile.label.toUpperCase()}</div><h2>${esc(file.name)}</h2><div class="qr-wrap"><canvas id="qr"></canvas><div class="scanline"></div></div><div class="progress"><div id="bar"></div></div><div class="stats wide"><div><span>QR FPS</span><b>${profile.fps}</b></div><div><span>PAYLOAD</span><b>${profile.blockSize} B</b></div><div><span>SEMBOL</span><b id="frame">0</b></div><div><span>YAYIN</span><b id="sent">0 KB</b></div></div><p class="hint" id="sendHint">Cihazları sabit tutun. Parlaklığı yükseltmek okumayı hızlandırır.</p><div class="button-row"><button class="secondary" id="pause">Duraklat</button><button class="secondary" id="fullscreen">Tam ekran</button></div></section>`);document.querySelector('#finish').onclick=home;document.querySelector('#pause').onclick=e=>{state.paused=!state.paused;e.currentTarget.textContent=state.paused?'Devam et':'Duraklat';if(!state.paused)renderLoop(profile);};document.querySelector('#fullscreen').onclick=()=>document.querySelector('.qr-wrap').requestFullscreen?.();renderLoop(profile);}
async function renderLoop(profile){if(!state.running||state.paused)return;const started=performance.now(),isManifest=state.symbolId%16===0;let frame;if(isManifest)frame=JSON.stringify(state.manifest);else{const payload=bytesToBase64(createSymbol(state.blocks,state.symbolId));frame=JSON.stringify({p:PROTOCOL,t:'d',id:state.manifest.id,s:state.symbolId,d:payload,x:checksum(payload)});}try{await QRCode.toCanvas(document.querySelector('#qr'),frame,{width:380,margin:2,errorCorrectionLevel:isManifest?'M':profile.level,color:{dark:'#03060c',light:'#fff'}});state.symbolId++;const elapsed=(performance.now()-state.startedAt)/1000;document.querySelector('#frame').textContent=state.symbolId.toLocaleString('tr-TR');document.querySelector('#sent').textContent=`${(state.symbolId*profile.blockSize/1024).toFixed(0)} KB`;document.querySelector('#bar').style.width=`${(state.symbolId%(state.blocks.length*3))/(state.blocks.length*3)*100}%`;document.querySelector('#sendHint').textContent=`${time(elapsed)} · Sistematik bloklar ve kurtarma sembolleri birlikte yayınlanıyor.`;}catch(error){document.querySelector('#sendHint').textContent=`QR üretilemedi: ${error.message}`;state.running=false;return;}state.sendTimer=setTimeout(()=>renderLoop(profile),Math.max(0,1000/profile.fps-(performance.now()-started)));}
function receivePage(){stopAll();state.manifest=null;state.decoder=null;state.valid=state.duplicate=state.invalid=0;shell(`<section class="panel receive"><button class="back" data-home>← Ana sayfa</button><div class="eyebrow">ALICI · QRB2</div><h2>Kayıp toleranslı tarama</h2><p>QR kodu çerçevenin çoğunu dolduracak şekilde hizalayın. Sistem kaçan kareleri yeni sembollerle telafi eder.</p><button class="primary" id="camera">Kamerayı aç <span>⌗</span></button><div id="scanner"></div></section>`);document.querySelector('[data-home]').onclick=home;document.querySelector('#camera').onclick=startCamera;}
async function startCamera(){try{state.stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080},frameRate:{ideal:60}}});await requestWakeLock();document.querySelector('#scanner').innerHTML=`<div class="camera"><video id="video" playsinline muted></video><div class="target"><i></i><i></i><i></i><i></i></div><div class="camera-status">OTOMATİK ODAK · MERKEZ TARAMA</div></div><canvas id="capture" hidden></canvas><div class="receive-info"><div><b id="filename">Aktarım bekleniyor…</b><small id="count">Manifest QR kodu aranıyor</small></div><strong id="percent">0%</strong></div><div class="progress"><div id="receiveBar"></div></div><div class="mini-stats"><span>Çözülen <b id="valid">0</b></span><span>Tekrar <b id="dupe">0</b></span><span>Bozuk <b id="bad">0</b></span><span>Hız <b id="goodput">0 KB/s</b></span></div>`;document.querySelector('#camera').remove();const video=document.querySelector('#video');video.srcObject=state.stream;await video.play();state.startedAt=performance.now();state.lastScan=0;scan(performance.now());}catch(error){document.querySelector('#scanner').innerHTML=`<div class="error">Kamera açılamadı. HTTPS ve kamera iznini kontrol edin.<small>${esc(error.message)}</small></div>`;}}
function scan(now){const video=document.querySelector('#video'),canvas=document.querySelector('#capture');if(!video||!state.stream)return;if(video.readyState>=2&&now-state.lastScan>=33){state.lastScan=now;const source=Math.min(video.videoWidth,video.videoHeight)*.92,sx=(video.videoWidth-source)/2,sy=(video.videoHeight-source)/2,target=Math.min(960,source);canvas.width=target;canvas.height=target;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(video,sx,sy,source,source,0,0,target,target);const image=ctx.getImageData(0,0,target,target),code=jsQR(image.data,target,target,{inversionAttempts:'dontInvert'});if(code)acceptFrame(code.data);}state.scanId=requestAnimationFrame(scan);}
function acceptFrame(text){let f;try{f=JSON.parse(text);}catch{return;}if(f.p!==PROTOCOL)return;if(f.t==='m'){if(state.manifest&&state.manifest.id!==f.id)return;if(!state.manifest){state.manifest=f;state.decoder=new FountainDecoder(f.k,f.b);}updateReceive();return;}if(!state.manifest||f.id!==state.manifest.id||f.t!=='d')return;if(checksum(f.d)!==f.x){state.invalid++;updateReceive();return;}const payload=base64ToBytes(f.d);if(payload.length!==state.manifest.b){state.invalid++;updateReceive();return;}const result=state.decoder.add(f.s,payload);if(result.duplicate)state.duplicate++;else state.valid++;updateReceive();if(state.decoder.complete)finishReceive();}
function updateReceive(){if(!state.manifest)return;const solved=state.decoder?.solved||0,percent=Math.floor(solved/state.manifest.k*100),elapsed=Math.max(.1,(performance.now()-state.startedAt)/1000),goodput=solved*state.manifest.b/elapsed/1024;document.querySelector('#filename').textContent=state.manifest.n;document.querySelector('#count').textContent=`${solved} / ${state.manifest.k} kaynak blok · ${time(elapsed)}`;document.querySelector('#percent').textContent=`${percent}%`;document.querySelector('#receiveBar').style.width=`${percent}%`;document.querySelector('#valid').textContent=state.valid;document.querySelector('#dupe').textContent=state.duplicate;document.querySelector('#bad').textContent=state.invalid;document.querySelector('#goodput').textContent=`${goodput.toFixed(1)} KB/s`;}
async function finishReceive(){cancelAnimationFrame(state.scanId);state.stream?.getTracks().forEach(t=>t.stop());const raw=state.decoder.assemble(state.manifest.z),digest=hex(await crypto.subtle.digest('SHA-256',raw));if(digest!==state.manifest.h){document.querySelector('#scanner').innerHTML='<div class="error">SHA‑256 eşleşmedi. Güvenlik nedeniyle dosya kaydedilmedi.</div>';return;}const url=URL.createObjectURL(new Blob([raw],{type:state.manifest.m}));document.querySelector('#scanner').innerHTML=`<div class="complete"><span>✓</span><h2>Kayıpsız doğrulandı</h2><p>Dosyanın SHA‑256 özeti göndericiyle birebir eşleşti.</p><div class="verified">SHA‑256 VERIFIED</div><div class="file-card"><div class="file-icon">◆</div><div><b>${esc(state.manifest.n)}</b><small>${size(state.manifest.z)} · ${state.valid} sembol okundu</small></div></div><a class="primary" href="${url}" download="${esc(state.manifest.n)}">Dosyayı kaydet <span>↓</span></a><button class="secondary" id="again">Yeni dosya al</button></div>`;document.querySelector('#again').onclick=receivePage;}
async function requestWakeLock(){try{state.wakeLock=await navigator.wakeLock?.request('screen');}catch{}}
function stopAll(){state.running=false;clearTimeout(state.sendTimer);cancelAnimationFrame(state.scanId);state.stream?.getTracks().forEach(t=>t.stop());state.wakeLock?.release?.().catch(()=>{});state.stream=null;state.wakeLock=null;}
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&state.running)requestWakeLock();});window.addEventListener('beforeunload',stopAll);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));home();
