import QRCode from 'qrcode';
import jsQR from 'jsqr';
import './style.css';

const app = document.querySelector('#app');
const state = { stream: null, scanId: 0, sending: false, sendTimer: 0, chunks: [], received: new Map(), manifest: null, startedAt: 0, valid: 0, duplicate: 0, invalid: 0 };

const esc = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const size = n => n < 1024 ? `${n} B` : n < 1048576 ? `${(n/1024).toFixed(1)} KB` : `${(n/1048576).toFixed(1)} MB`;
const bytesTo64 = bytes => { let s=''; for(let i=0;i<bytes.length;i+=0x8000)s+=String.fromCharCode(...bytes.subarray(i,i+0x8000)); return btoa(s); };
const b64ToBytes = s => Uint8Array.from(atob(s), c => c.charCodeAt(0));
const hex = bytes => [...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('');
const crc = str => { let c=0x811c9dc5; for(let i=0;i<str.length;i++){c^=str.charCodeAt(i); c=Math.imul(c,0x01000193);} return (c>>>0).toString(36); };

function shell(content){ app.innerHTML=`<div class="glow"></div><header><button class="brand" data-home><span class="logo">▦</span> QRBEAM</button><span class="secure"><i></i> Cihaz içinde</span></header><main>${content}</main><footer>Sunucu yok · Hesap yok · Yalnızca ışık</footer>`; document.querySelector('[data-home]')?.addEventListener('click', home); }
function home(){ stopAll(); shell(`<section class="hero"><div class="eyebrow">OPTİK DOSYA AKTARIMI</div><h1>Dosyanı havadan değil,<br><em>ışıktan geçir.</em></h1><p>Wi‑Fi, Bluetooth veya yükleme olmadan. Bir ekrandan diğer kameraya, doğrudan.</p><div class="choices"><button class="choice" id="send"><span class="choice-icon">↗</span><b>Dosya Gönder</b><small>Dosyayı hareketli QR akışına dönüştür</small><span class="arrow">→</span></button><button class="choice" id="receive"><span class="choice-icon purple">⌗</span><b>Dosya Al</b><small>Kamerayla QR akışını tara ve kaydet</small><span class="arrow">→</span></button></div><div class="privacy"><span>◈</span><div><b>Verilerin sana ait kalır</b><small>Dosyalar ve kamera görüntüsü bu cihazdan ayrılmaz.</small></div></div></section>`); document.querySelector('#send').onclick=sendPage; document.querySelector('#receive').onclick=receivePage; }

function sendPage(){ stopAll(); shell(`<section class="panel"><button class="back" data-home>← Ana sayfa</button><div class="eyebrow">GÖNDERİCİ</div><h2>Bir dosya seç</h2><p>Her tür dosya desteklenir. Bu ilk sürüm küçük dosyalar için optimize edilmiştir.</p><label class="drop"><input id="file" type="file"><span class="upload">↑</span><b>Dosya seçmek için dokun</b><small>Önerilen üst sınır: 2 MB</small></label><div id="fileInfo"></div></section>`); document.querySelector('[data-home]').onclick=home; document.querySelector('#file').onchange=prepareFile; }
async function prepareFile(e){ const file=e.target.files[0]; if(!file)return; const box=document.querySelector('#fileInfo'); box.innerHTML=`<div class="loading">Dosya hazırlanıyor…</div>`; const raw=new Uint8Array(await file.arrayBuffer()); const digest=hex(await crypto.subtle.digest('SHA-256',raw)); const chunkSize=360; const id=crypto.randomUUID().slice(0,8); const chunks=[]; for(let i=0;i<raw.length;i+=chunkSize) chunks.push(bytesTo64(raw.slice(i,i+chunkSize))); const manifest={p:'QRB1',t:'m',id,n:file.name,z:file.size,m:file.type||'application/octet-stream',h:digest,c:chunks.length}; state.chunks=[JSON.stringify(manifest),...chunks.map((d,i)=>JSON.stringify({p:'QRB1',t:'d',id,i,d,x:crc(d)}))]; box.innerHTML=`<div class="file-card"><div class="file-icon">◆</div><div><b>${esc(file.name)}</b><small>${size(file.size)} · ${chunks.length} QR parçası</small></div></div><div class="notice">Aktarım boyunca iki cihazı sabit tutun. İlk kare dosya bilgilerini taşır.</div><button class="primary" id="start">QR aktarımını başlat <span>→</span></button>`; document.querySelector('#start').onclick=()=>startSending(file,manifest); }
function startSending(file,manifest){ state.sending=true; state.startedAt=Date.now(); shell(`<section class="transmit"><button class="back" id="finish">← Bitir</button><div class="eyebrow live"><i></i> YAYINDA</div><h2>${esc(file.name)}</h2><div class="qr-wrap"><canvas id="qr"></canvas><div class="scanline"></div></div><div class="progress"><div id="bar"></div></div><div class="stats"><div><span>KARE</span><b id="frame">0</b></div><div><span>BOYUT</span><b>${size(file.size)}</b></div><div><span>HIZ</span><b>8 FPS</b></div></div><p class="hint">Alıcı cihazın kamerasını QR koduna doğrultun.</p><button class="secondary" id="pause">Duraklat</button></section>`); document.querySelector('#finish').onclick=home; let i=0, paused=false; const tick=async()=>{if(paused)return; const index=i%state.chunks.length; await QRCode.toCanvas(document.querySelector('#qr'),state.chunks[index],{width:300,margin:2,errorCorrectionLevel:'L',color:{dark:'#05070d',light:'#ffffff'}}); document.querySelector('#frame').textContent=i; document.querySelector('#bar').style.width=`${((index+1)/state.chunks.length)*100}%`; i++;}; tick(); state.sendTimer=setInterval(tick,125); document.querySelector('#pause').onclick=e=>{paused=!paused;e.currentTarget.textContent=paused?'Devam et':'Duraklat';}; }

function receivePage(){ stopAll(); state.received.clear(); state.manifest=null; state.valid=state.duplicate=state.invalid=0; shell(`<section class="panel receive"><button class="back" data-home>← Ana sayfa</button><div class="eyebrow">ALICI</div><h2>QR akışını tara</h2><p>Kamera izni verdikten sonra gönderici ekrandaki QR'ı çerçeveye hizalayın.</p><button class="primary" id="camera">Kamerayı aç <span>⌗</span></button><div id="scanner"></div></section>`); document.querySelector('[data-home]').onclick=home; document.querySelector('#camera').onclick=startCamera; }
async function startCamera(){ try{ state.stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{facingMode:{ideal:'environment'},width:{ideal:1280},height:{ideal:720}}}); const s=document.querySelector('#scanner'); s.innerHTML=`<div class="camera"><video id="video" playsinline muted></video><div class="target"><i></i><i></i><i></i><i></i></div></div><canvas id="capture" hidden></canvas><div class="receive-info"><div><b id="filename">Aktarım bekleniyor…</b><small id="count">QR kodunu çerçeveye alın</small></div><strong id="percent">0%</strong></div><div class="progress"><div id="receiveBar"></div></div><div class="mini-stats"><span>Geçerli <b id="valid">0</b></span><span>Tekrar <b id="dupe">0</b></span><span>Bozuk <b id="bad">0</b></span></div>`; document.querySelector('#camera').remove(); const video=document.querySelector('#video'); video.srcObject=state.stream; await video.play(); state.startedAt=Date.now(); scan(); }catch(err){ document.querySelector('#scanner').innerHTML=`<div class="error">Kamera açılamadı. HTTPS üzerinden açtığınızdan ve kamera izni verdiğinizden emin olun.<small>${esc(err.message)}</small></div>`; } }
function scan(){ const video=document.querySelector('#video'), canvas=document.querySelector('#capture'); if(!video||!state.stream)return; if(video.readyState>=2){ const w=video.videoWidth,h=video.videoHeight; canvas.width=w;canvas.height=h;const ctx=canvas.getContext('2d',{willReadFrequently:true});ctx.drawImage(video,0,0,w,h);const img=ctx.getImageData(0,0,w,h);const code=jsQR(img.data,w,h,{inversionAttempts:'dontInvert'});if(code) acceptFrame(code.data); } state.scanId=requestAnimationFrame(scan); }
function acceptFrame(text){ let f; try{f=JSON.parse(text);}catch{return;} if(f.p!=='QRB1')return; if(f.t==='m'){ if(state.manifest&&state.manifest.id!==f.id)return; state.manifest=f; updateReceive(); return;} if(!state.manifest||f.id!==state.manifest.id||f.t!=='d')return; if(crc(f.d)!==f.x){state.invalid++;updateReceive();return;} if(state.received.has(f.i)){state.duplicate++;updateReceive();return;} state.received.set(f.i,f.d);state.valid++;updateReceive();if(state.received.size===state.manifest.c) finishReceive(); }
function updateReceive(){ if(!state.manifest)return; const p=Math.floor(state.received.size/state.manifest.c*100); document.querySelector('#filename').textContent=state.manifest.n; document.querySelector('#count').textContent=`${state.received.size} / ${state.manifest.c} parça`;document.querySelector('#percent').textContent=`${p}%`;document.querySelector('#receiveBar').style.width=`${p}%`;document.querySelector('#valid').textContent=state.valid;document.querySelector('#dupe').textContent=state.duplicate;document.querySelector('#bad').textContent=state.invalid; }
async function finishReceive(){ cancelAnimationFrame(state.scanId); state.stream?.getTracks().forEach(t=>t.stop()); const parts=[];for(let i=0;i<state.manifest.c;i++)parts.push(b64ToBytes(state.received.get(i)));const total=parts.reduce((n,p)=>n+p.length,0),raw=new Uint8Array(total);let at=0;for(const p of parts){raw.set(p,at);at+=p.length;}const digest=hex(await crypto.subtle.digest('SHA-256',raw));if(digest!==state.manifest.h){document.querySelector('#scanner').innerHTML=`<div class="error">Dosya doğrulanamadı. Aktarımı yeniden deneyin.</div>`;return;}const blob=new Blob([raw],{type:state.manifest.m});const url=URL.createObjectURL(blob);document.querySelector('#scanner').innerHTML=`<div class="complete"><span>✓</span><h2>Aktarım tamamlandı</h2><p>SHA‑256 doğrulandı. Dosya bozulmadan ulaştı.</p><div class="file-card"><div class="file-icon">◆</div><div><b>${esc(state.manifest.n)}</b><small>${size(state.manifest.z)}</small></div></div><a class="primary" href="${url}" download="${esc(state.manifest.n)}">Dosyayı kaydet <span>↓</span></a><button class="secondary" id="again">Yeni dosya al</button></div>`;document.querySelector('#again').onclick=receivePage; }
function stopAll(){clearInterval(state.sendTimer);cancelAnimationFrame(state.scanId);state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;state.sending=false;}
window.addEventListener('beforeunload',stopAll);if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));home();
